// Generated by Proto compiler, DO NOT EDIT
// source: c++.capnp

#ifndef CAPNP_INCLUDED_bdf87d7bb8304e81_
#define CAPNP_INCLUDED_bdf87d7bb8304e81_

#include <capnp/generated-header-support.h>

#if CAPNP_VERSION != 7000
#error "Version mismatch between generated code and library headers.  You must use the same version of the Cap'n Proto compiler and library."
#endif


namespace capnp {
namespace schemas {

CAPNP_DECLARE_SCHEMA(b9c6f99ebf805f2c);
CAPNP_DECLARE_SCHEMA(f264a779fef191ce);
CAPNP_DECLARE_SCHEMA(cf38185663ac13e6);
CAPNP_DECLARE_SCHEMA(df32b128842485a7);
CAPNP_DECLARE_SCHEMA(e3a9296d348aaa3b);

}  // namespace schemas
}  // namespace capnp



namespace capnp {
namespace annotations {

// =======================================================================================

// =======================================================================================

}  // namespace
}  // namespace

#endif  // CAPNP_INCLUDED_bdf87d7bb8304e81_
